class Global {
  static List<Map<dynamic, dynamic>> item = [
    {
      'name': 'Note Book',
      'image': 'asset/image/book.jpeg',
      'itemList': notebook,
      'length': notebook.length
    },
    {
      'name': 'Pen',
      'image': 'asset/image/pen.jpeg',
      'itemList': pen,
      'length': pen.length
    },
    {
      'name': 'Pencil',
      'image': 'asset/image/pencil.jpeg',
      'itemList': pencil,
      'length': pencil.length
    },
    {
      'name': 'Eraser',
      'image': 'asset/image/eraser.jpeg',
      'itemList': eraser,
      'length': eraser.length
    },
    {
      'name': 'Calculator',
      'image': 'asset/image/calculator.jpeg',
      'itemList': calculator,
      'length': calculator.length
    },
    {
      'name': 'Text Book',
      'image': 'asset/image/textBook.jpeg',
      'itemList': textbook,
      'length': textbook.length
    },
    {
      'name': 'Folders',
      'image': 'asset/image/scale.png',
      'itemList': folders,
      'length': folders.length
    },
    {
      'name': 'Crayons',
      'image': 'asset/image/crayon.jpeg',
      'itemList': crayon,
      'length': crayon.length
    },
    {
      'name': 'Drawing Book',
      'image': 'asset/image/drawing.jpeg',
      'itemList': drawing,
      'length': drawing.length
    },
    {
      'name': 'Chart Paper',
      'image': 'asset/image/chart paper.jpeg',
      'itemList': chart,
      'length': chart.length
    },
    {
      'name': 'Water Colour',
      'image': 'asset/image/watercolor.jpeg',
      'itemList': watercolor,
      'length': watercolor.length
    },
    {
      'name': 'Glue Sticks',
      'image': 'asset/image/glue.jpeg',
      'itemList': glue,
      'length': glue.length
    },
    {
      'name': 'Highlighter Pens',
      'image': 'asset/image/highlighter.jpeg',
      'itemList': highlight,
      'length': highlight.length
    },
    {
      'name': 'Cello Tap',
      'image': 'asset/image/cello tap.jpeg',
      'itemList': tap,
      'length': tap.length
    },
    {
      'name': 'Paint Brush',
      'image': 'asset/image/paintbrush.png',
      'itemList': brush,
      'length': brush.length
    },
    {
      'name': 'Envelope',
      'image': 'asset/image/envelope.jpeg',
      'itemList': envelope,
      'length': envelope.length
    }
  ];
  static List<Map<dynamic, dynamic>> notebook = [
    {
      'name': 'NoteBook',
      'image': 'asset/image/nb1.jpeg',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'ClassMate',
      'image': 'asset/image/cm.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'HardCover',
      'image': 'asset/image/hc.jpeg',
      'price': 180,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Journal',
      'image': 'asset/image/journal.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'BlankBook',
      'image': 'asset/image/blank.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'PersonalDiary',
      'image': 'asset/image/pd.jpeg',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'SpiralBook',
      'image': 'asset/image/spiral.jpeg',
      'price': 70,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'WallMart',
      'image': 'asset/image/wm.jpeg',
      'price': 130,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    }
  ];
  static List<Map<dynamic, dynamic>> pen = [
    {
      'name': 'Cello Griper',
      'image': 'asset/image/cellop.png',
      'price': 10,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Pin Point',
      'image': 'asset/image/pin.png',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'GelPen',
      'image': 'asset/image/gel.png',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'ColorPen',
      'image': 'asset/image/color.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Saino Softek',
      'image': 'asset/image/softec.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Fountain Pen',
      'image': 'asset/image/fountain.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'ButterFellow',
      'image': 'asset/image/butterfelow.png',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Lexi',
      'image': 'asset/image/Lexi.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> pencil = [
    {
      'name': 'NatRaj',
      'image': 'asset/image/natraj.png',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Apsra',
      'image': 'asset/image/apsra (1).jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Doms',
      'image': 'asset/image/doms.png',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Fun',
      'image': 'asset/image/fun.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Lead Pencil',
      'image': 'asset/image/lead.png',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Paper Pencil',
      'image': 'asset/image/paper.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Sketch Pencil',
      'image': 'asset/image/sketch.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Color Pencil',
      'image': 'asset/image/color pencil.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> eraser = [
    {
      'name': 'Eraser',
      'image': 'asset/image/eraser1.jpeg',
      'price': 10,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Big Eraser',
      'image': 'asset/image/eraser2.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Fruit Eraser',
      'image': 'asset/image/eraser3.jpeg',
      'price': 15,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Sliding Eraser',
      'image': 'asset/image/eraser4.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Emoji Eraser',
      'image': 'asset/image/eraser5.jpeg',
      'price': 10,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> calculator = [
    {
      'name': 'Simple',
      'image': 'asset/image/simple.jpeg',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Casio',
      'image': 'asset/image/casio.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Scientific',
      'image': 'asset/image/scientific.jpeg',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Laptop',
      'image': 'asset/image/laptop.jpeg',
      'price': 250,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> textbook = [
    {
      'name': 'History',
      'image': 'asset/image/text1.jpeg',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'English',
      'image': 'asset/image/text2.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Maths',
      'image': 'asset/image/text3.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Science',
      'image': 'asset/image/text4.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Geography',
      'image': 'asset/image/text5.jpeg',
      'price': 180,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Economics',
      'image': 'asset/image/text6.jpeg',
      'price': 70,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Anatomy',
      'image': 'asset/image/text7.jpeg',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'General Knowledge',
      'image': 'asset/image/text8.jpeg',
      'price': 140,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Biology',
      'image': 'asset/image/text9.jpeg',
      'price': 320,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Chemistry',
      'image': 'asset/image/text10.jpeg',
      'price': 210,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Physics',
      'image': 'asset/image/text11.jpeg',
      'price': 250,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> folders = [
    {
      'name': 'File',
      'image': 'asset/image/folder4.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Presentation Folder',
      'image': 'asset/image/folder3.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Ring Folder',
      'image': 'asset/image/folder2.jpeg',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Book Folder',
      'image': 'asset/image/folder5.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Plastic Folder',
      'image': 'asset/image/folder1.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> crayon = [
    {
      'name': 'Wax Crayon',
      'image': 'asset/image/crayon1.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Doms Crayon',
      'image': 'asset/image/crayon2.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Plastic Crayon',
      'image': 'asset/image/crayon3.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> drawing = [
    {
      'name': 'Drawing Book',
      'image': 'asset/image/db1.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Brustro',
      'image': 'asset/image/db2.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Sketch Book',
      'image': 'asset/image/db3.jpeg',
      'price': 120,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Thick Paper',
      'image': 'asset/image/db4.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Large Book',
      'image': 'asset/image/db5.jpeg',
      'price': 180,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> chart = [
    {
      'name': 'Color Paper ',
      'image': 'asset/image/cp1.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Multi Size Paper',
      'image': 'asset/image/cp2.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Project Paper',
      'image': 'asset/image/cp3.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Decoration Paper',
      'image': 'asset/image/cp4.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> watercolor = [
    {
      'name': 'Tube Color',
      'image': 'asset/image/wc1.jpeg',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Cake Water Color',
      'image': 'asset/image/wc2.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Poster Water Color',
      'image': 'asset/image/wc3.jpeg',
      'price': 180,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Poster Water Color ',
      'image': 'asset/image/wc4.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> glue = [
    {
      'name': 'Glue Stick',
      'image': 'asset/image/g1.jpeg',
      'price': 20,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Gun Glue',
      'image': 'asset/image/g2.jpeg',
      'price': 80,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Fevicol',
      'image': 'asset/image/g3.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Glue Bottle',
      'image': 'asset/image/g4.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Super Glue',
      'image': 'asset/image/g5.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> highlight = [
    {
      'name': 'Yellow Pen',
      'image': 'asset/image/h1.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Red Pen',
      'image': 'asset/image/h2.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Blue Pen',
      'image': 'asset/image/h3.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Green Pen',
      'image': 'asset/image/h4.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Pink Pen',
      'image': 'asset/image/h5.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> tap = [
    {
      'name': '1 Inch Tap',
      'image': 'asset/image/c1.jpeg',
      'price': 15,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': '2 Inch Tap',
      'image': 'asset/image/c2.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Brown Tap',
      'image': 'asset/image/c3.jpeg',
      'price': 30,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Paper Tap',
      'image': 'asset/image/c4.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Double Tap',
      'image': 'asset/image/c5.jpeg',
      'price': 40,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Red Double Tap',
      'image': 'asset/image/c6.jpeg',
      'price': 70,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> brush = [
    {
      'name': 'Set of 4 Brush',
      'image': 'asset/image/b1.jpeg',
      'price': 70,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Set of 7 Brush',
      'image': 'asset/image/b2.jpeg',
      'price': 200,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'RSet of 12 Brush',
      'image': 'asset/image/b3.jpeg',
      'price': 350,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Detail Brush',
      'image': 'asset/image/b4.jpeg',
      'price': 150,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Round Point Brush',
      'image': 'asset/image/b5.jpeg',
      'price': 250,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static List<Map<dynamic, dynamic>> envelope = [
    {
      'name': 'Quilled Pack of 5',
      'image': 'asset/image/e1.jpeg',
      'price': 100,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Brown Envelope',
      'image': 'asset/image/e2.jpeg',
      'price': 10,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Marriage Card',
      'image': 'asset/image/e3.jpeg',
      'price': 70,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
    {
      'name': 'Calligraphy Card',
      'image': 'asset/image/e4.jpeg',
      'price': 50,
      'cart': false,
      'i': 0,
      'total': 0,
      'add': false,
      'remove': false,
    },
  ];
  static Set<Map<dynamic, dynamic>> cart = {};
  static List<Map<dynamic, dynamic>> finalCart = [];

  static num totalBill = 0;
}
